name: Action Test

on:
  pull_request:

jobs:
  action-test:
    name: Action Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install npm Packages Using This Action
        uses: chvmvd/npm-packages-install-action@v1.0.0
